#include "vision_analyzer/calibration.hpp"

#include <algorithm>
#include <cmath>
#include <ostream>
#include <vector>

namespace vision_analyzer {
namespace {

[[nodiscard]] double median_or_zero(std::vector<double> values) {
    if (values.empty()) {
        return 0.0;
    }
    std::sort(values.begin(), values.end());
    const std::size_t middle = values.size() / 2;
    if (values.size() % 2 == 1) {
        return values[middle];
    }
    return (values[middle - 1] + values[middle]) * 0.5;
}

}  // namespace

CalibrationFit fit_hid_calibration(
    const std::vector<CalibrationSample>& samples,
    int calibration_step_counts
) {
    std::vector<double> x_gains;
    std::vector<double> y_gains;
    std::vector<double> noise_values;
    int movement_samples = 0;
    int noise_samples = 0;

    for (const auto& sample : samples) {
        if (sample.counts_dx == 0 && sample.counts_dy == 0) {
            noise_values.push_back(cv::norm(sample.visual_shift));
            ++noise_samples;
            continue;
        }

        if (sample.counts_dx != 0 && std::abs(sample.visual_shift.x) >= 0.75) {
            x_gains.push_back(std::abs(static_cast<double>(sample.counts_dx) / sample.visual_shift.x));
            ++movement_samples;
        }
        if (sample.counts_dy != 0 && std::abs(sample.visual_shift.y) >= 0.75) {
            y_gains.push_back(std::abs(static_cast<double>(sample.counts_dy) / sample.visual_shift.y));
            ++movement_samples;
        }
    }

    CalibrationFit fit;
    fit.gain_x = median_or_zero(x_gains);
    fit.gain_y = median_or_zero(y_gains);
    fit.noise_px = median_or_zero(noise_values);
    fit.noise_samples = noise_samples;
    fit.movement_samples = movement_samples;

    std::vector<double> axis_gains;
    if (fit.gain_x > 0.0 && std::isfinite(fit.gain_x)) {
        axis_gains.push_back(fit.gain_x);
    }
    if (fit.gain_y > 0.0 && std::isfinite(fit.gain_y)) {
        axis_gains.push_back(fit.gain_y);
    }
    fit.hid_gain = median_or_zero(axis_gains);
    fit.valid = fit.hid_gain > 0.0 && std::isfinite(fit.hid_gain);
    fit.deadzone_px = std::clamp(std::ceil(std::max(0.5, fit.noise_px * 3.0)), 1.0, 8.0);
    fit.max_step = std::clamp(calibration_step_counts * 3, 20, 240);
    return fit;
}

void write_hid_tuning_config(std::ostream& output, const Options& options, const CalibrationFit& fit) {
    output << "# Generated by vision_analyzer --calibrate-hid\n"
           << "input=" << input_source_name(options.input_source) << '\n'
           << "dxgi_adapter=" << options.dxgi_adapter << '\n'
           << "dxgi_output=" << options.dxgi_output << '\n'
           << "dxgi_timeout_ms=" << options.dxgi_timeout_ms << '\n'
           << "dxgi_gpu_preference=" << dxgi_gpu_preference_name(options.dxgi_gpu_preference) << '\n'
           << "hid_gain=" << fit.hid_gain << '\n'
           << "hid_max_step=" << fit.max_step << '\n'
           << "hid_deadzone_px=" << fit.deadzone_px << '\n'
           << "body_head_anchor_ratio=" << options.tuning.body_head_anchor_ratio << '\n'
           << "kalman_process_noise=" << options.tuning.kalman_process_noise << '\n'
           << "kalman_measurement_noise=" << options.tuning.kalman_measurement_noise << '\n'
           << "kalman_error_covariance=" << options.tuning.kalman_error_covariance << '\n';
}

}  // namespace vision_analyzer
